/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant Software (64-bit) 2.0.1.281.2
    Soft IP Version: 1.0.0
    Mon Mar 23 14:45:18 2020
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module Sine_LUT (rd_clk_i, rst_i, rd_en_i, rd_clk_en_i, rd_addr_i, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rd_clk_i;
    input  rst_i;
    input  rd_en_i;
    input  rd_clk_en_i;
    input  [10:0]  rd_addr_i;
    output  [15:0]  rd_data_o;
endmodule