/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.7 */
/* Fri Feb 07 15:41:31 2020 */

/* parameterized module instance */
OscPll __ (.CLKI( ), .CLKOP( ));
