/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.7 */
/* Tue Feb 11 11:43:20 2020 */

/* parameterized module instance */
OscPll __ (.CLKI( ), .CLKOP( ));
