/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 7.5 */
/* Sat Feb 29 16:06:41 2020 */

/* parameterized module instance */
SamplePos_RAM __ (.Clock( ), .ClockEn( ), .Reset( ), .WE( ), .Address( ), 
    .Data( ), .Q( ));
