/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 7.5 */
/* Tue Feb 25 11:42:39 2020 */

/* parameterized module instance */
SamplePos_RAM __ (.Clock( ), .ClockEn( ), .Reset( ), .WE( ), .Address( ), 
    .Data( ), .Q( ));
