/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.4 */
/* Tue Feb 25 11:09:01 2020 */

/* parameterized module instance */
SineLUT __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
