/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.4 */
/* Fri Feb 07 12:38:33 2020 */

/* parameterized module instance */
SineLUT __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
