/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant Software (64-bit) 2.0.1.281.2
    Soft IP Version: 1.1.0
    Thu Apr 23 11:28:32 2020
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module Ring_Mod_Mult (clk_i, clk_en_i, rst_i, data_a_i, data_b_i, result_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  clk_en_i;
    input  rst_i;
    input  [19:0]  data_a_i;
    input  [19:0]  data_b_i;
    output  [39:0]  result_o;
endmodule